#!/bin/bash
#!/bin/sh

file_path="/tmp/iamafile"

# Check if the file exists
if [ -e "$file_path" ]; then
    file_type=$(file -b "$file_path")
    echo "The type of file 'iamafile' is: $file_type"
else
    echo "File 'iamafile' does not exist in the /tmp directory."
fi
